Create CRUD for analyses
AASS-Team/aass-frontend-service pull request #4
Opened 2022-05-03 15:55 UTC by nikoleta01

2022-05-03 21:11 UTC, MCFreddie777 requested changes
Good job, left some comments.

2022-05-03 21:11 UTC, MCFreddie777 commented on src/router/index.ts
> +			// {
Unnecessary comment.

2022-05-03 21:11 UTC, MCFreddie777 commented on src/router/index.ts
> +					// {
Comment here as well. Please remove it.

2022-05-03 21:11 UTC, MCFreddie777 commented on src/store/user/user.types.ts
> +	analyses: User[];
```typescript
users: User[];
user: User;
```

2022-05-03 21:11 UTC, MCFreddie777 commented on src/views/Analysis/AnalysisCreate.vue
> +			console.log(this.analysis);
`console.log`

2022-05-03 21:11 UTC, MCFreddie777 commented on src/views/Analysis/AnalysisCreate.vue
> +			if (this.analysis) {
Unnecessary check. This analysis is always present, as it it in the `data` function.

2022-05-03 21:11 UTC, MCFreddie777 commented on src/views/Analysis/AnalysisCreate.vue
> +		this.fetchLabs();
Idea: `Promise.all` and show loader maybe? (as all are promises)

2022-05-03 21:11 UTC, MCFreddie777 commented on src/views/Analysis/AnalysisEdit.vue
> +			this.analysis.tools = this.analysis.tools.splice(index, 1); // 2nd parameter means remove one item only
Uneccessary coment, everybody knows what `Array.splice` does.

2022-05-03 21:11 UTC, MCFreddie777 commented on src/views/Analysis/AnalysisEdit.vue
> +		this.fetchAnalysis(this.$route.params.id).finally(() => {
So, only when analysis is fetched, the loader is hidden? What about the other async assets as fetchlabs or fetchTools? 

Please use `Promise.all()` and then disable the loader.

2022-05-03 21:16 UTC, nikoleta01 commented on src/store/user/user.types.ts
> +	analyses: User[];
good catch

2022-05-04 08:20 UTC, MCFreddie777 approved these changes

2022-05-04 08:21 UTC, merged